package com.sunbaby.english;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.sunbaby.english.dto.guardian.CreateGuardianRequest;
import com.sunbaby.english.dto.student.CreateStudentRequest;
import com.sunbaby.english.dto.student.UpdateStudentRequest;
import com.sunbaby.english.entity.SchoolGrade;
import com.sunbaby.english.entity.enums.Gender;
import com.sunbaby.english.repository.EnrollmentRepository;
import com.sunbaby.english.repository.GuardianRepository;
import com.sunbaby.english.repository.SchoolGradeRepository;
import com.sunbaby.english.repository.StudentGuardianRepository;
import com.sunbaby.english.repository.StudentRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.security.test.context.support.WithMockUser;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.web.servlet.MockMvc;

import java.time.LocalDate;

import static org.hamcrest.Matchers.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@SpringBootTest
@AutoConfigureMockMvc
@ActiveProfiles("test")
public class StudentControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private ObjectMapper objectMapper;

    @Autowired
    private StudentRepository studentRepository;

    @Autowired
    private StudentGuardianRepository studentGuardianRepository;

    @Autowired
    private GuardianRepository guardianRepository;

    @Autowired
    private EnrollmentRepository enrollmentRepository;

    @Autowired
    private SchoolGradeRepository schoolGradeRepository;

    private SchoolGrade testGrade;

    @BeforeEach
    void setUp() {
        enrollmentRepository.deleteAll();
        studentGuardianRepository.deleteAll();
        guardianRepository.deleteAll();
        studentRepository.deleteAll();
        schoolGradeRepository.deleteAll();

        testGrade = schoolGradeRepository.save(SchoolGrade.builder()
                .name("Grade 2")
                .displayOrder(2)
                .active(true)
                .build());
    }

    @Test
    @WithMockUser(username = "teacher", authorities = {"ROLE_TEACHER"})
    void testTeacherCanRegisterStudentWithAutoGeneratedCode() throws Exception {
        CreateStudentRequest request = CreateStudentRequest.builder()
                .firstName("Kavindu")
                .lastName("Silva")
                .dateOfBirth(LocalDate.of(2018, 5, 14))
                .gender(Gender.MALE)
                .schoolGradeId(testGrade.getId())
                .phone("0771234567")
                .email("kavindu@gmail.com")
                .address("123 Temple Road, Colombo")
                .build();

        mockMvc.perform(post("/api/v1/students")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.success").value(true))
                .andExpect(jsonPath("$.data.firstName").value("Kavindu"))
                .andExpect(jsonPath("$.data.lastName").value("Silva"))
                .andExpect(jsonPath("$.data.studentCode", startsWith("SB-")))
                .andExpect(jsonPath("$.data.schoolGradeName").value("Grade 2"));
    }

    @Test
    @WithMockUser(username = "teacher", authorities = {"ROLE_TEACHER"})
    void testRegisterStudentWithEmbeddedGuardian() throws Exception {
        CreateGuardianRequest guardian = CreateGuardianRequest.builder()
                .name("Sunil Silva")
                .relationship("Father")
                .phone("0719876543")
                .email("sunil@silva.lk")
                .isPrimary(true)
                .build();

        CreateStudentRequest request = CreateStudentRequest.builder()
                .firstName("Amaya")
                .lastName("Silva")
                .dateOfBirth(LocalDate.of(2019, 8, 20))
                .gender(Gender.FEMALE)
                .schoolGradeId(testGrade.getId())
                .primaryGuardian(guardian)
                .build();

        mockMvc.perform(post("/api/v1/students")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.data.guardians", hasSize(1)))
                .andExpect(jsonPath("$.data.guardians[0].name").value("Sunil Silva"))
                .andExpect(jsonPath("$.data.guardians[0].primary").value(true));
    }

    @Test
    @WithMockUser(username = "teacher", authorities = {"ROLE_TEACHER"})
    void testDuplicateCustomStudentCodeFails() throws Exception {
        CreateStudentRequest request1 = CreateStudentRequest.builder()
                .studentCode("SB-CUSTOM-001")
                .firstName("John")
                .lastName("Doe")
                .build();

        mockMvc.perform(post("/api/v1/students")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request1)))
                .andExpect(status().isCreated());

        CreateStudentRequest request2 = CreateStudentRequest.builder()
                .studentCode("SB-CUSTOM-001")
                .firstName("Jane")
                .lastName("Doe")
                .build();

        mockMvc.perform(post("/api/v1/students")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request2)))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.success").value(false))
                .andExpect(jsonPath("$.message", containsString("already in use")));
    }

    @Test
    @WithMockUser(username = "teacher", authorities = {"ROLE_TEACHER"})
    void testAddGuardianToExistingStudent() throws Exception {
        CreateStudentRequest request = CreateStudentRequest.builder()
                .firstName("Dinuka")
                .lastName("Perera")
                .build();

        String response = mockMvc.perform(post("/api/v1/students")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isCreated())
                .andReturn().getResponse().getContentAsString();

        Long studentId = objectMapper.readTree(response).path("data").path("id").asLong();

        CreateGuardianRequest guardianRequest = CreateGuardianRequest.builder()
                .name("Malini Perera")
                .relationship("Mother")
                .phone("0775551234")
                .isPrimary(true)
                .build();

        mockMvc.perform(post("/api/v1/students/" + studentId + "/guardians")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(guardianRequest)))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.data.name").value("Malini Perera"))
                .andExpect(jsonPath("$.data.relationship").value("Mother"));
    }
}
